package ru.vad1mchk.progr.lab05.client.util

/**
 * Annotation for all fields tht are automatically generated
 * and are not to be input
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FIELD)
annotation class AutoGenerated()
